# Imports for the common reusable components
from frontend.custom_dash_components.common.color_metrics import ColorMetrics
from frontend.custom_dash_components.common.bottom_notification import BottomNotification

# Imports for the top manage panel
from frontend.custom_dash_components.manage_panel.file_upload import FileUpload
from frontend.custom_dash_components.manage_panel.select_ocr_module import SelectOcrModule
from frontend.custom_dash_components.manage_panel.select_language import SelectLanguage

# Imports for the recognition results container
from frontend.custom_dash_components.recognition_results.copy_to_clipboard import CopyClipboardButton
from frontend.custom_dash_components.recognition_results.text_container import TextContainer

# Imports for the character analysis container
from frontend.custom_dash_components.character_analysis.character_analysis_color_metrics import CharacterAnalysisColorMetrics
from frontend.custom_dash_components.character_analysis.symbol_type_radio_group import SymbolTypeRadioGroup
from frontend.custom_dash_components.character_analysis.accuracy_radio_group import AccuracyRadioGroup

